### ISSUE TITLE
Exposed Username and password in URI

### ISSUE THREAD

**Issue by eth0izzle** [data-voyage-solutions/OAG_project_work#1]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@test-oag-db.cknjqxktq50p.us-east-2.rds.amazonaws.com` in file [/Resources/Session_5/session_5.ipynb](https://github.com/data-voyage-solutions/OAG_project_work/blob/master/Resources/Session_5/session_5.ipynb)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by kgracia44** [comment]
Thanks! resolved, for the most part.
